version: '3.9'

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    env_file: ./.env
    environment:
      - DATABASE_URL=$DATABASE_URL
    volumes:
      - ./:/app
      - /app/node_modules
      - ./prisma:/app/prisma
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - db
    depends_on:
      - db
    # command: ['npm', 'run', 'prisma:deploy']

  db:
    container_name: db
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - '5432:5432'
    expose:
      - '5432'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
