FROM node:18 as build

RUN apt update && apt install libssl-dev -y --no-install-recommends  

# Copy Dir
COPY . ./app

# Work to Dir
WORKDIR /app

# Install Node Package
RUN npm install --legacy-peer-deps

# Set Env
ENV NODE_ENV development

EXPOSE 3000

# RUN npx prisma migrate deploy
RUN npx prisma generate

# Cmd script
CMD ["npm", "run", "dev"]
